language: java

jdk:
  # - oraclejdk8
  # - oraclejdk7
  # - openjdk8
  - openjdk7

branches:
  only:
    - master

script:
  # - mvn clean install
  - cd SalesTaxesCalculator
  - mvn test
  # - mvn cobertura:cobertura
