language: java

env:
  - JDK=oraclejdk8
  - JDK=openjdk8
dist: trusty
before_script:
  - jdk_switcher use $JDK

jdk:
  # - oraclejdk8
  # - oraclejdk7
  - openjdk8
  # - openjdk7

branches:
  only:
    - master

script:
  # - mvn clean install
  - cd SalesTaxesCalculator
  - mvn test
  # - mvn cobertura:cobertura
